# name: Packer Build
# on:  
#   push:
#   pull_request:
#     branches:
#       - master
# jobs:
#   packer_build:
#     runs-on: ubuntu-latest
#     steps:
#       # - uses: actions/checkout@v1
#       - name: Packer build
#         # uses: ExitoLab/packer_build_action_aws@v0.2.10
#         # with:
#         #   templateFile: 'packer-example.json'
#         #   workingDir: 'packer'
#           # varFile: 'variables.json'
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: us-east-1
      
#       - name: pwd
#         run:  pwd
#         shell: bash

#       - name: permissions
#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/packer && chmod 400 packerbuild.sh
#         shell: bash

#       - name: test packer build
#         run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/scripts && sh packerbuild.sh
#         shell: bash
name: Packer Build
on:  
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      
      # - name: permissions
      #   run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/packer && chmod 700 packerbuild.sh && chmod 700 packer-example.json
      #   shell: bash

      - name: test packer build
        run: cd /home/runner/work/elite-gh-actions-tfc/elite-gh-actions-tfc/scripts && sh packerbuild.sh
        shell: bash
        