name: Packer Build
on:  
  push:
  pull_request:
    branches:
      - master
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: script
        run: packer/packerbuild.sh
        shell: bash
        with:
         password: ${{ secrets.ACCESS_TOKEN }}     

